module.exports = {
  allLanguages: {
    EN: 'EN',
    ES: 'ES',
    ES_ES: 'ES_ES',
  },
  allLanguageSlugs: {
    EN: 'en',
    ES: 'es',
  },
  allContinents: {
    GLOBAL: 'GLOBAL',
    AFRICA: 'AFRICA',
    ASIA: 'ASIA',
    AUSTRALIA: 'AUSTRALIA',
    EUROPE: 'EUROPE',
    NORTH_AMERICA: 'NORTH_AMERICA',
    SOUTH_AMERICA: 'SOUTH_AMERICA',
  },
  allPageTypes: {
    ABOUT: 'ABOUT',
    ARTICLE: 'ARTICLE',
    CAREERS: 'CAREERS',
    CONTACT: 'CONTACT',
    EVENTS: 'EVENTS',
    HISTORY: 'HISTORY',
    HOPE: 'HOPE',
    INDUSTRY: 'INDUSTRY',
    LANDING: 'LANDING',
    LEADERSHIP: 'LEADERSHIP',
    NEWS: 'NEWS',
    PRODUCT: 'PRODUCT',
    PROMO: 'PROMO',
    SERVICE: 'SERVICE',
    USED: 'USED',
  },
  allRegions: {
    NORTH_AMERICA: 'NORTH_AMERICA',
    SOUTH_AMERICA: 'SOUTH_AMERICA',
    CENTRAL_SOUTH_AMERICA: 'CENTRAL_SOUTH_AMERICA',
  },
  allRegionSlugs: {
    NORTH_AMERICA: 'northamerica',
    SOUTH_AMERICA: 'southamerica',
    CENTRAL_SOUTH_AMERICA: 'centralsouthamerica',
  },
  allBrands: {
    ALMEX_IN_A_BOX: 'ALMEX_IN_A_BOX',
    ALMEX_INSTITUTE: 'ALMEX_INSTITUTE',
    BAT: 'BAT',
    EMSYS: 'EMSYS',
    FUSION: 'FUSION',
    GLOBAL_SERVICES: 'GLOBAL_SERVICES',
    VOTECH: 'VOTECH',
  },
  allOptions: {
    PSI_100: 'PSI_100',
    PSI_200: 'PSI_200',
    RECTANGULAR: 'RECTANGULAR',
    RHOMBOID: 'RHOMBOID',
  },
  allThemes: {
    HEAVYWEIGHT: 'HEAVYWEIGHT',
    LIGHTWEIGHT: 'LIGHTWEIGHT',
    INDUSTRIAL: 'INDUSTRIAL',
    FUSION_HOT: 'FUSION_HOT',
    FUSION_COLD: 'FUSION_COLD',
  },
};
