module.exports = {
  allBrands: {
    ALMEX_IN_A_BOX: 'ALMEX_IN_A_BOX',
    ALMEX_INSTITUTE: 'ALMEX_INSTITUTE',
    BAT: 'BAT',
    EMSYS: 'EMSYS',
    FUSION: 'FUSION',
    GLOBAL_SERVICES: 'GLOBAL_SERVICES',
    VOTECH: 'VOTECH',
  },
  allContinents: {
    GLOBAL: 'GLOBAL',
    AFRICA: 'AFRICA',
    ASIA: 'ASIA',
    AUSTRALIA: 'AUSTRALIA',
    EUROPE: 'EUROPE',
    NORTH_AMERICA: 'NORTH_AMERICA',
    SOUTH_AMERICA: 'SOUTH_AMERICA',
  },
  allLanguages: {
    EN: 'EN',
    ES: 'ES',
    ES_ES: 'ES_ES',
  },
  allLanguageSlugs: {
    EN: 'en',
    ES: 'es',
  },
  allLandingTypes: {
    BRAND: 'BRAND',
    INDUSTRY: 'INDUSTRY',
    PRODUCT: 'PRODUCT',
  },
  allOffices: {
    API: 'INDONESIA',
    AUS: 'AUSTRALIA',
    BRA: 'BRASIL',
    CHI: 'CHILE',
    CHN: 'CHINA',
    EUR: 'EUROPE',
    GER: 'GERMANY',
    IND: 'INDIA',
    USA: 'UNITED_STATES',
    CAN: 'CANADA',
    AFR: 'AFRICA',
    MEX: 'MEXICO',
    PER: 'PERU',
    FON: 'FONMAR',
  },
  allPageTypes: {
    ABOUT: 'ABOUT',
    ARTICLE: 'ARTICLE',
    CAREERS: 'CAREERS',
    CONTACT: 'CONTACT',
    EVENTS: 'EVENTS',
    HISTORY: 'HISTORY',
    HOMEPAGE: 'HOMEPAGE',
    HOPE: 'HOPE',
    INDUSTRY: 'INDUSTRY',
    INSTITUTE: 'INSTITUTE',
    LANDING: 'LANDING',
    LEADERSHIP: 'LEADERSHIP',
    NEWS: 'NEWS',
    PRODUCT: 'PRODUCT',
    PROMO: 'PROMO',
    SERVICES: 'SERVICES',
    USED: 'USED',
  },
  allRegions: {
    NORTH_AMERICA: 'NORTH_AMERICA',
    SOUTH_AMERICA: 'SOUTH_AMERICA',
    CENTRAL_SOUTH_AMERICA: 'CENTRAL_SOUTH_AMERICA',
  },
  allRegionSlugs: {
    NORTH_AMERICA: 'northamerica',
    SOUTH_AMERICA: 'southamerica',
    CENTRAL_SOUTH_AMERICA: 'centralsouthamerica',
  },

  allOptions: {
    MULTI_PLATEN: 'MULTI_PLATEN',
    PSI_40: 'PSI_40',
    PSI_60: 'PSI_60',
    PSI_100: 'PSI_100',
    PSI_175: 'PSI_175',
    PSI_200: 'PSI_200',
    RECTANGULAR: 'RECTANGULAR',
    RHOMBOID: 'RHOMBOID',
    SIDE_BY_SIDE_RECT: 'SIDE_BY_SIDE_RECT',
    SIDE_BY_SIDE_RHOM: 'SIDE_BY_SIDE_RHOM',
    SIDE_HANDLES: 'SIDE_HANDLES',
  },
  allThemes: {
    HEAVYWEIGHT: 'HEAVYWEIGHT',
    LIGHTWEIGHT: 'LIGHTWEIGHT',
    INDUSTRIAL: 'INDUSTRIAL',
    FUSION_HOT: 'FUSION_HOT',
    FUSION_COLD: 'FUSION_COLD',
  },
};
